### PR TITLE
Get the stuff up to date

### PR DESCRIPTION
**Pull request by totbas1**

### CODE REVIEW

**Comment by TheGamer1002** [comment]
image
oh lord

**Review by TheGamer1002 — APPROVED** [review]
Looks good

**Comment by TheGamer1002** [comment]
At this point I just need one more reviewer. Requesting review from everyone.

**Review by TheGamer1002 — APPROVED** [review]

**Review by joseph-hughes — APPROVED** [review]

**Comment by joseph-hughes** [comment]
My review doesn't count for much, since I just have read access to this repo

**Pull request merged**
